export type ComparisonCategory =
  | "makanan" | "wisata" | "militer"
  | "teknologi" | "infrastruktur" | "global"
  | "luar-angkasa" | "olahraga" | "hiburan" | "kesehatan"

export interface ComparisonItem {
  id: string
  emoji: string
  name: string
  description: string
  unitPrice: number
  unit: string
  category: ComparisonCategory
  featured?: boolean
  source?: string
}

export const COMPARISONS: ComparisonItem[] = [
  // ── MAKANAN ────────────────────────────────────────────────
  {
    id: "nasi-padang",
    emoji: "🍛",
    name: "Nasi Padang",
    description: "Porsi nasi padang standard warung",
    unitPrice: 15_000,
    unit: "porsi",
    category: "makanan",
  },
  {
    id: "gudeg-jogja",
    emoji: "🍚",
    name: "Gudeg Jogja",
    description: "Porsi gudeg komplit",
    unitPrice: 25_000,
    unit: "porsi",
    category: "makanan",
  },
  {
    id: "indomie-goreng",
    emoji: "🫙",
    name: "Indomie Goreng",
    description: "Per bungkus indomie goreng",
    unitPrice: 3_500,
    unit: "bungkus",
    category: "makanan",
    featured: true,
  },
  {
    id: "gorengan",
    emoji: "🧆",
    name: "Gorengan (1 biji)",
    description: "Satu biji tempe atau tahu goreng",
    unitPrice: 2_000,
    unit: "biji",
    category: "makanan",
  },

  // ── WISATA ─────────────────────────────────────────────────
  {
    id: "tiket-bali",
    emoji: "✈️",
    name: "Tiket PP ke Bali",
    description: "Tiket pesawat pergi-pulang dari Jakarta",
    unitPrice: 500_000,
    unit: "tiket",
    category: "wisata",
  },
  {
    id: "trip-lombok",
    emoji: "🏝️",
    name: "Liburan Lombok 3D2N",
    description: "Estimasi all-in budget trip",
    unitPrice: 1_500_000,
    unit: "trip",
    category: "wisata",
  },

  // ── MILITER ────────────────────────────────────────────────
  {
    id: "gerald-ford",
    emoji: "⚓",
    name: "Kapal Induk USS Gerald Ford",
    description: "Kapal induk terbesar AS senilai ~USD 13.3B",
    unitPrice: 213_000_000_000_000,
    unit: "kapal",
    category: "militer",
    featured: true,
  },
  {
    id: "jet-f35",
    emoji: "🛩️",
    name: "Jet Tempur F-35 Lightning II",
    description: "Pesawat tempur siluman tercanggih AS ~USD 100M",
    unitPrice: 1_550_000_000_000,
    unit: "pesawat",
    category: "militer",
  },
  {
    id: "tank-leopard",
    emoji: "🪖",
    name: "Tank Tempur Leopard 2A4",
    description: "Main battle tank Eropa ~USD 7M",
    unitPrice: 108_500_000_000,
    unit: "tank",
    category: "militer",
  },
  {
    id: "kapal-selam",
    emoji: "🐋",
    name: "Kapal Selam Tipe 209",
    description: "Kapal selam konvensional ~USD 500M",
    unitPrice: 7_750_000_000_000,
    unit: "kapal",
    category: "militer",
  },
  {
    id: "rudal-tomahawk",
    emoji: "🚀",
    name: "Rudal Jelajah Tomahawk",
    description: "Rudal presisi jarak jauh AS ~USD 1.87M",
    unitPrice: 28_985_000_000,
    unit: "rudal",
    category: "militer",
  },

  // ── TEKNOLOGI ──────────────────────────────────────────────
  {
    id: "iphone-16-pro",
    emoji: "📱",
    name: "iPhone 16 Pro Max",
    description: "Varian 256GB",
    unitPrice: 23_999_000,
    unit: "unit",
    category: "teknologi",
    featured: true,
  },
  {
    id: "macbook-pro",
    emoji: "💻",
    name: "MacBook Pro M4",
    description: "Base model 14-inch M4",
    unitPrice: 28_999_000,
    unit: "unit",
    category: "teknologi",
  },
  {
    id: "motor-listrik",
    emoji: "🛵",
    name: "Motor Listrik",
    description: "Motor listrik entry-level (Gesits/Volta)",
    unitPrice: 30_000_000,
    unit: "unit",
    category: "teknologi",
  },

  // ── INFRASTRUKTUR ──────────────────────────────────────────
  {
    id: "puskesmas",
    emoji: "🏥",
    name: "Puskesmas Baru",
    description: "Estimasi biaya bangun 1 Puskesmas",
    unitPrice: 2_000_000_000,
    unit: "puskesmas",
    category: "infrastruktur",
  },
  {
    id: "guru-gaji",
    emoji: "🎓",
    name: "Gaji Guru 1 Bulan",
    description: "UMR guru non-PNS rata-rata",
    unitPrice: 500_000,
    unit: "guru",
    category: "infrastruktur",
  },
  {
    id: "rumah-subsidi",
    emoji: "🏠",
    name: "Rumah Subsidi",
    description: "Rumah subsidi FLPP",
    unitPrice: 185_000_000,
    unit: "unit",
    category: "infrastruktur",
  },
  {
    id: "jalan-tol",
    emoji: "🛣️",
    name: "Jalan Tol 1 KM",
    description: "Estimasi biaya konstruksi per KM",
    unitPrice: 100_000_000_000,
    unit: "km",
    category: "infrastruktur",
  },
  {
    id: "ambulans",
    emoji: "🚑",
    name: "Ambulans Baru",
    description: "Unit ambulans standar Kemenkes",
    unitPrice: 400_000_000,
    unit: "unit",
    category: "infrastruktur",
  },
  {
    id: "beasiswa-kuliah",
    emoji: "📚",
    name: "Beasiswa Kuliah 1 Tahun",
    description: "UKT PTN rata-rata nasional",
    unitPrice: 8_000_000,
    unit: "mahasiswa",
    category: "infrastruktur",
  },

  // ── GLOBAL ─────────────────────────────────────────────────
  {
    id: "gdp-timor-leste",
    emoji: "🌏",
    name: "GDP Timor Leste 1 Tahun",
    description: "Total PDB Timor Leste ~USD 3B (2023)",
    unitPrice: 46_500_000_000_000,
    unit: "negara",
    category: "global",
  },
  {
    id: "anggaran-who",
    emoji: "🏛️",
    name: "Anggaran WHO 1 Tahun",
    description: "Total anggaran Organisasi Kesehatan Dunia ~USD 6B",
    unitPrice: 93_000_000_000_000,
    unit: "tahun",
    category: "global",
  },

  // ── LUAR ANGKASA ───────────────────────────────────────────
  {
    id: "anggaran-nasa",
    emoji: "🔭",
    name: "Anggaran NASA 1 Tahun",
    description: "Total anggaran tahunan NASA ~USD 25.4B",
    unitPrice: 393_700_000_000_000,
    unit: "tahun",
    category: "luar-angkasa",
    featured: true,
  },
  {
    id: "roket-falcon9",
    emoji: "🚀",
    name: "Roket Falcon 9 SpaceX",
    description: "Biaya peluncuran Falcon 9 ~USD 67M",
    unitPrice: 1_038_500_000_000,
    unit: "roket",
    category: "luar-angkasa",
  },
  {
    id: "roket-starship",
    emoji: "🛸",
    name: "1 Launch Starship SpaceX",
    description: "Estimasi biaya 1 kali peluncuran Starship ~USD 100M",
    unitPrice: 1_550_000_000_000,
    unit: "launch",
    category: "luar-angkasa",
  },
  {
    id: "teleskop-webb",
    emoji: "🌌",
    name: "Teleskop James Webb",
    description: "Total biaya pengembangan JWST ~USD 10B",
    unitPrice: 155_000_000_000_000,
    unit: "teleskop",
    category: "luar-angkasa",
  },
  {
    id: "satelit-komunikasi",
    emoji: "📡",
    name: "Satelit Komunikasi",
    description: "Biaya produksi + peluncuran satelit ~USD 200M",
    unitPrice: 3_100_000_000_000,
    unit: "satelit",
    category: "luar-angkasa",
  },
  {
    id: "iss-biaya",
    emoji: "🛰️",
    name: "Biaya Bangun ISS",
    description: "Total biaya konstruksi ISS ~USD 150B",
    unitPrice: 2_325_000_000_000_000,
    unit: "stasiun",
    category: "luar-angkasa",
  },

  // ── OLAHRAGA ───────────────────────────────────────────────
  {
    id: "transfer-neymar",
    emoji: "⚽",
    name: "Transfer Neymar ke PSG",
    description: "Rekor transfer terbesar sepanjang masa ~€222M (2017)",
    unitPrice: 3_800_000_000_000,
    unit: "transfer",
    category: "olahraga",
    featured: true,
  },
  {
    id: "gaji-mbappe",
    emoji: "🏃",
    name: "Gaji Mbappé per Tahun",
    description: "Gaji tahunan Kylian Mbappé ~€200M",
    unitPrice: 3_400_000_000_000,
    unit: "tahun",
    category: "olahraga",
  },
  {
    id: "formula1-mobil",
    emoji: "🏎️",
    name: "Mobil Formula 1",
    description: "Biaya produksi 1 mobil F1 ~USD 15M",
    unitPrice: 232_500_000_000,
    unit: "mobil",
    category: "olahraga",
  },
  {
    id: "stadion-gbk",
    emoji: "🏟️",
    name: "Renovasi Stadion GBK",
    description: "Total biaya renovasi Gelora Bung Karno 2018",
    unitPrice: 1_200_000_000_000,
    unit: "stadion",
    category: "olahraga",
  },
  {
    id: "tiket-final-worldcup",
    emoji: "🏆",
    name: "Tiket Final Piala Dunia",
    description: "Tiket resmi final FIFA World Cup ~USD 1.500",
    unitPrice: 23_250_000,
    unit: "tiket",
    category: "olahraga",
  },

  // ── HIBURAN ────────────────────────────────────────────────
  {
    id: "konser-taylorswift",
    emoji: "🎤",
    name: "Tiket Konser Taylor Swift",
    description: "Tiket Eras Tour kategori Golden (front floor)",
    unitPrice: 5_000_000,
    unit: "tiket",
    category: "hiburan",
  },
  {
    id: "budget-gta6",
    emoji: "🎮",
    name: "Budget Dev GTA 6",
    description: "Estimasi biaya pengembangan GTA VI ~USD 2B",
    unitPrice: 31_000_000_000_000,
    unit: "game",
    category: "hiburan",
  },
  {
    id: "film-endgame",
    emoji: "🎬",
    name: "Budget Film Avengers Endgame",
    description: "Total budget produksi + pemasaran ~USD 356M",
    unitPrice: 5_518_000_000_000,
    unit: "film",
    category: "hiburan",
  },
  {
    id: "netflix-bulan",
    emoji: "📺",
    name: "Netflix Premium 1 Bulan",
    description: "Langganan Netflix paket Premium",
    unitPrice: 65_000,
    unit: "bulan",
    category: "hiburan",
  },
  {
    id: "spotify-tahun",
    emoji: "🎵",
    name: "Spotify Premium 1 Tahun",
    description: "Langganan Spotify Premium tahunan",
    unitPrice: 659_880,
    unit: "tahun",
    category: "hiburan",
  },

  // ── KESEHATAN ──────────────────────────────────────────────
  {
    id: "vaksin-covid",
    emoji: "💉",
    name: "Vaksin COVID-19 per Dosis",
    description: "Harga vaksin COVID-19 per dosis program pemerintah",
    unitPrice: 50_000,
    unit: "dosis",
    category: "kesehatan",
  },
  {
    id: "operasi-jantung",
    emoji: "❤️",
    name: "Operasi Bypass Jantung",
    description: "Biaya operasi CABG di RS swasta Jakarta",
    unitPrice: 150_000_000,
    unit: "operasi",
    category: "kesehatan",
  },
  {
    id: "obat-kanker",
    emoji: "🧬",
    name: "Terapi Kanker 1 Bulan",
    description: "Biaya kemoterapi/imunoterapi standar per bulan",
    unitPrice: 25_000_000,
    unit: "bulan",
    category: "kesehatan",
  },
  {
    id: "rsud-baru",
    emoji: "🏨",
    name: "RS Umum Daerah Tipe B",
    description: "Estimasi biaya pembangunan RSUD Tipe B",
    unitPrice: 200_000_000_000,
    unit: "RS",
    category: "kesehatan",
  },
  {
    id: "dialisis-setahun",
    emoji: "🩺",
    name: "Cuci Darah 1 Pasien/Tahun",
    description: "Biaya hemodialisis 3x/minggu selama 1 tahun",
    unitPrice: 120_000_000,
    unit: "pasien",
    category: "kesehatan",
  },
]
